import { Translation } from './types';

export const TRANSLATIONS: Record<'en' | 'ur', Translation> = {
  en: {
    dashboard: "Dashboard",
    transactions: "Transactions",
    goals: "Savings Goals",
    advisor: "AI Advisor",
    totalBalance: "Total Balance",
    income: "Income",
    expenses: "Expenses",
    recentActivity: "Recent Activity",
    addTransaction: "Add Transaction",
    description: "Description",
    amount: "Amount",
    category: "Category",
    date: "Date",
    add: "Add",
    cancel: "Cancel",
    save: "Save",
    aiAdvisorTitle: "Arman Sheraz AI Financial Advisor",
    aiAdvisorDesc: "Get personalized tips to save money based on your spending habits.",
    askAdvisor: "Analyze my finances",
    loading: "Analyzing...",
    language: "Language",
    welcome: "Welcome back, Arman",
    savingProgress: "Saving Progress",
    addNewGoal: "Add New Goal",
    target: "Target",
    saved: "Saved",
    type: "Type"
  },
  ur: {
    dashboard: "ڈیش بورڈ",
    transactions: "لین دین",
    goals: "بچت کے اہداف",
    advisor: "AI مشیر",
    totalBalance: "کل بیلنس",
    income: "آمدنی",
    expenses: "اخراجات",
    recentActivity: "حالیہ سرگرمیاں",
    addTransaction: "لین دین شامل کریں",
    description: "تفصیل",
    amount: "رقم",
    category: "زمرہ",
    date: "تاریخ",
    add: "شامل کریں",
    cancel: "منسوخ کریں",
    save: "محفوظ کریں",
    aiAdvisorTitle: "ارمان شیراز AI مالیاتی مشیر",
    aiAdvisorDesc: "اپنی اخراجات کی عادات کی بنیاد پر پیسے بچانے کے لیے ذاتی تجاویز حاصل کریں۔",
    askAdvisor: "میرے مالیات کا تجزیہ کریں",
    loading: "تجزیہ ہو رہا ہے...",
    language: "زبان",
    welcome: "خوش آمدید، ارمان",
    savingProgress: "بچت کی پیشرفت",
    addNewGoal: "نیا ہدف شامل کریں",
    target: "ہدف",
    saved: "محفوظ شدہ",
    type: "قسم"
  }
};